import type { Concept } from "./concepts-types";
const P = (key: string, label: string, unit: string, min: number, max: number, step: number, def: number) => ({ key, label, unit, min, max, step, default: def });
const C = (x: Concept) => x;
export const PART: Concept[] = [
C({id:"length-contraction",slug:"length-contraction",title:"Length Contraction",category:"relativity",difficulty:"intermediate",
tagline:"A moving rod is shorter along its motion only.",
description:"Compare proper length with the lab length.",
intuition:"The same γ that stretches time squeezes parallel length.",
explanation:"L = L0/γ from simultaneous end-point events in the lab.",
theory:"Lorentz transformation of the rod’s ends.",
assumptions:["Special relativity"],
equations:[{latex:"L=L_0/\\gamma",meaning:"Length contraction.",symbols:"L0 proper length"}],
parameters:[P("beta","v/c","",0,0.995,0.005,0.7),P("L0","Proper length","m",1,20,0.5,10)],
related:["time-dilation","spacetime-diagram"],measurements:["L","gamma"]}),
C({id:"spacetime-diagram",slug:"spacetime-diagram",title:"Spacetime Diagram",category:"relativity",difficulty:"advanced",
tagline:"Light cones, worldlines, and the meaning of now.",
description:"Minkowski diagram with c=1. Boost tilts axes.",
intuition:"You cannot outrun your light cone.",
explanation:"A boost is a hyperbolic rotation. Flat spacetime, not GR.",
theory:"Lorentz group in 1+1 D. Relativity of simultaneity.",
assumptions:["1+1 D","Flat spacetime"],
equations:[{latex:"c^2t^2-x^2=const",meaning:"Invariant interval.",symbols:"c=1 units on the plot"}],
parameters:[P("beta","Boost v/c","",-0.9,0.9,0.01,0.4)],
related:["time-dilation","length-contraction"],measurements:["gamma"]}),
C({id:"quantum-double-slit",slug:"quantum-double-slit",title:"Quantum Double Slit",category:"quantum",difficulty:"advanced",
tagline:"Clicks build an interference pattern. No hidden classical path.",
description:"Detections sampled from |ψ|² of a two-slit amplitude. Born rule — not a time-dependent Schrödinger solve.",
intuition:"Each hit is local. The pattern is statistical.",
explanation:"Born rule. Which-path mix replaces fringes with a single-slit envelope.",
theory:"No trajectories through one slit are drawn.",
assumptions:["Monochromatic packet","Which-path slider is a mix, not full decoherence dynamics"],
equations:[{latex:"P(x)\\propto|\\psi_1+\\psi_2|^2",meaning:"Born rule.",symbols:"ψ amplitude"}],
parameters:[P("lambda","Wavelength","nm",380,700,5,500),P("d","Slit spacing","μm",20,300,5,100),P("which","Which-path mix","",0,1,0.01,0)],
related:["double-slit","particle-in-a-box"],measurements:["counts"]}),
C({id:"quantum-tunneling",slug:"quantum-tunneling",title:"Quantum Tunneling",category:"quantum",difficulty:"advanced",
tagline:"E < V is not a hard wall for a wave function.",
description:"Rectangular barrier with analytic transmission.",
intuition:"Thicker or taller barriers starve T exponentially below the barrier.",
explanation:"Exact 1D scattering formula. Sketch of |ψ| is qualitative.",
theory:"Stationary Schrödinger matching at edges.",
assumptions:["1D","Rectangular barrier"],
equations:[{latex:"T\\sim e^{-2\\kappa L}",meaning:"Thick-barrier trend, E<V.",symbols:"κ=√(2m(V-E))/ℏ"}],
parameters:[P("E","Energy E","eV",0.2,12,0.1,4),P("V","Barrier V","eV",1,16,0.1,8),P("L","Width","nm",0.05,1.2,0.01,0.35)],
related:["particle-in-a-box"],measurements:["T","R"]}),
C({id:"particle-in-a-box",slug:"particle-in-a-box",title:"Particle in a Box",category:"quantum",difficulty:"intermediate",
tagline:"Standing waves of probability.",
description:"Infinite square well. Change n and width.",
intuition:"|ψ|² is where detections happen — not a bouncing marble.",
explanation:"ψn = √(2/L) sin(nπx/L), En ∝ n²/L².",
theory:"Same mode structure as a guitar string.",
assumptions:["Infinite walls","1D","Non-relativistic"],
equations:[{latex:"E_n=n^2\\pi^2\\hbar^2/2mL^2",meaning:"Energy eigenvalues.",symbols:"n=1,2,3…"}],
parameters:[P("n","Level n","",1,8,1,2),P("L","Width","nm",0.3,4,0.05,1),P("mix","Mix n+1","",0,1,0.01,0)],
related:["standing-waves","quantum-tunneling"],measurements:["E"]}),
C({id:"solar-system",slug:"solar-system",title:"Solar System",category:"astrophysics",difficulty:"beginner",
tagline:"Educational visualization with Kepler III period ratios.",
description:"Inner planets on Keplerian ellipses. Distances compressed. Not an N-body solver.",
intuition:"Mercury snaps around. Distances are compressed on purpose.",
explanation:"Periods follow T² ∝ a³. Not an N-body integration.",
theory:"Keplerian heliocentric orbits.",
assumptions:["Sun fixed","Radii schematic"],
equations:[{latex:"T^2\\propto a^3",meaning:"Kepler’s third law.",symbols:"a semi-major axis"}],
parameters:[P("speed","Time rate","×",0.2,12,0.1,2)],
related:["orbital-motion","black-hole"],measurements:["day"]}),
C({id:"black-hole",slug:"black-hole",title:"Black Hole (visualization)",category:"astrophysics",difficulty:"advanced",
tagline:"Schematic Schwarzschild geometry — not a rubber sheet, not full GR ray tracing.",
description:"Horizon, photon sphere, toy disk. Mass sets rs. Educational visualization.",
intuition:"Light can circle at 1.5 rs. Inside rs no escape to infinity.",
explanation:"rs = 2GM/c². Labeled visualization, not a full GR ray tracer.",
theory:"Schwarzschild metric scales.",
assumptions:["Non-spinning hole","Schematic optics"],
equations:[{latex:"r_s=2GM/c^2",meaning:"Schwarzschild radius.",symbols:"event horizon"}],
parameters:[P("M","Mass","M☉",3,30,0.5,10),P("spinLook","Disk tilt","deg",5,80,1,28)],
related:["orbital-motion","spacetime-diagram"],measurements:["rs","rph"]}),
];
