import type { Concept } from "./concepts-types";
const P = (key: string, label: string, unit: string, min: number, max: number, step: number, def: number) => ({ key, label, unit, min, max, step, default: def });
const C = (x: Concept) => x;
export const PART: Concept[] = [
C({id:"molecular-dynamics",slug:"molecular-dynamics",title:"Molecular Dynamics Gas",category:"thermodynamics",difficulty:"intermediate",dimension:"2D",audioAvailable:true,aliases:["hard disk"],simulationType:"hard-disk",tagline:"Hard disks. T from mean K.",description:"Elastic particle and wall hits. 2D toy MD.",intuition:"Hotter gas hits harder.",explanation:"Equal-mass 2D elastic collisions.",theory:"Hard-disk kinetic cartoon.",assumptions:["2D","No attraction"],equations:[{latex:"<K>=kT",meaning:"2D temperature.",symbols:"k"}],parameters:[P("T","Temperature","K",80,600,10,300),P("N","Particles","",10,80,2,36),P("box","Box scale","",0.7,1.4,0.05,1)],related:["ideal-gas","maxwell-boltzmann"],measurements:["T","P"],tryThis:"Raise T."}),
C({id:"maxwell-boltzmann",slug:"maxwell-boltzmann",title:"Maxwell-Boltzmann Distribution",category:"thermodynamics",difficulty:"intermediate",dimension:"2D",aliases:["speed distribution"],simulationType:"histogram",tagline:"Histogram hugs the theoretical curve.",description:"3D MB speeds as T changes.",intuition:"Hotter gas, hump slides right.",explanation:"f(v) ~ v^2 exp(-mv^2/2kT).",theory:"Ideal-gas speeds.",assumptions:["Ideal sampler"],equations:[{latex:"f(v)~v^2 e^{-mv^2/2kT}",meaning:"MB speeds.",symbols:"T kelvin"}],parameters:[P("T","Temperature","K",80,800,10,300),P("mass","Molar mass","g/mol",4,200,1,28)],related:["molecular-dynamics"],measurements:["vrms","vp"],tryThis:"Jump T 150 to 600."}),
C({id:"ray-tracing-3d",slug:"ray-tracing-3d",title:"3D Geometric Optics",category:"optics",difficulty:"intermediate",dimension:"3D",aliases:["mirror","lens"],simulationType:"geometric-optics",tagline:"Rays reflect and refract. Not photoreal.",description:"Thin lens plus Snell.",intuition:"Inside f the image is virtual.",explanation:"Geometric optics only.",theory:"Reflection and Snell.",assumptions:["Thin lens"],equations:[{latex:"n1 sin th1 = n2 sin th2",meaning:"Snell.",symbols:"from normal"}],parameters:[P("f","Focal length","cm",6,30,0.5,12),P("s","Object distance","cm",8,50,0.5,24),P("n2","n2","",1,1.8,0.01,1.5)],related:["lens"],measurements:["sprime","M"],tryThis:"Slide object inside f."}),
C({id:"spacetime-explorer",slug:"spacetime-explorer",title:"Relativistic Spacetime Explorer",category:"relativity",difficulty:"advanced",dimension:"2D",aliases:["minkowski"],simulationType:"minkowski",tagline:"Boosts tilt axes.",description:"Minkowski diagram with worldline and cone.",intuition:"Stay inside your light cone.",explanation:"1+1 D Lorentz boost.",theory:"Special relativity.",assumptions:["Flat spacetime"],equations:[{latex:"c^2 dtau^2 = c^2 dt^2 - dx^2",meaning:"Proper time.",symbols:"c=1"}],parameters:[P("beta","Boost v/c","",-0.9,0.9,0.01,0.5),P("x0","Event x","",-2,2,0.05,1)],related:["spacetime-diagram"],measurements:["gamma","tau"],tryThis:"Raise beta."}),
C({id:"relativistic-doppler",slug:"relativistic-doppler",title:"Relativistic Doppler Effect",category:"relativity",difficulty:"advanced",dimension:"2D",audioAvailable:true,aliases:["redshift"],simulationType:"analytic",tagline:"Receding sources go red.",description:"f' = f sqrt((1-beta)/(1+beta)).",intuition:"Near c receding, the tone drops.",explanation:"Longitudinal relativistic Doppler.",theory:"Special relativity.",assumptions:["Radial motion"],equations:[{latex:"f'=f sqrt((1-b)/(1+b))",meaning:"Receding if b>0.",symbols:"b=v/c"}],parameters:[P("f0","Emitted f","Hz",200,800,5,440),P("beta","v/c receding","",-0.95,0.95,0.01,0.3)],related:["doppler-effect"],measurements:["fobs","z"],tryThis:"Flip beta negative."}),
C({id:"quantum-harmonic-oscillator",slug:"quantum-harmonic-oscillator",title:"Quantum Harmonic Oscillator",category:"quantum",difficulty:"advanced",dimension:"2D",aliases:["qho"],simulationType:"stationary-schrodinger",tagline:"Evenly spaced rungs.",description:"Stationary states n=0..4.",intuition:"Ground state is a bump.",explanation:"E=hbar omega (n+1/2).",theory:"1D QHO eigenstates.",assumptions:["n<=4"],equations:[{latex:"E_n=hbar omega (n+1/2)",meaning:"Spectrum.",symbols:"n=0,1,..."}],parameters:[P("n","Level n","",0,4,1,1),P("omega","omega","",0.5,3,0.05,1),P("mix","Mix n+1","",0,1,0.01,0)],related:["particle-in-a-box"],measurements:["E"],tryThis:"Step n."}),
C({id:"hydrogen-orbitals",slug:"hydrogen-orbitals",title:"Hydrogen Orbital Explorer",category:"quantum",difficulty:"advanced",dimension:"3D",aliases:["1s","2p","orbital"],simulationType:"probability-cloud",tagline:"Probability cloud, not a miniature orbit.",description:"Monte Carlo |psi|^2 samples.",intuition:"p orbitals have a node plane.",explanation:"Hydrogenic forms.",theory:"Spinless hydrogenic orbitals.",assumptions:["No fine structure"],equations:[{latex:"P ~ |psi_nlm|^2",meaning:"Born density.",symbols:"n l m"}],parameters:[P("orb","0=1s .. 5=3d","",0,5,1,0),P("thresh","Density threshold","",0.02,0.6,0.01,0.12)],related:["quantum-harmonic-oscillator"],measurements:["n","l","m"],tryThis:"Switch to 2p and find the node."}),
C({id:"stern-gerlach",slug:"stern-gerlach",title:"Stern-Gerlach Experiment",category:"quantum",difficulty:"advanced",dimension:"2D",aliases:["spin"],simulationType:"two-outcome",tagline:"Two spots, not a smear.",description:"P(up)=cos^2(theta/2).",intuition:"90 degrees is a coin flip.",explanation:"Ideal spin-1/2 projector.",theory:"Spin-1/2.",assumptions:["Ideal analyzer"],equations:[{latex:"P_up=cos^2(theta/2)",meaning:"Born rule.",symbols:"theta"}],parameters:[P("theta","Prep angle","deg",0,180,1,40),P("shots","Burst size","",1,40,1,8)],related:["hydrogen-orbitals"],measurements:["up","down","P"],tryThis:"Set 0 degrees."}),
C({id:"star-system-3d",slug:"star-system-3d",title:"3D Star System",category:"astrophysics",difficulty:"intermediate",dimension:"3D",audioAvailable:true,aliases:["planet"],simulationType:"keplerian-toy",tagline:"Educational Keplerian planet.",description:"One star, one tilted ellipse. Not an ephemeris.",intuition:"Inclination is a rotated plane.",explanation:"Toy T^2 ~ a^3/M.",theory:"Fixed central mass.",assumptions:["Schematic distances"],equations:[{latex:"T^2 ~ a^3/M",meaning:"Kepler III toy.",symbols:"M star"}],parameters:[P("M","Star mass","x",0.5,3,0.05,1),P("m","Planet mass","x",0.1,2,0.05,0.3),P("inc","Inclination","deg",0,80,1,25),P("speed","Time rate","x",0.3,8,0.1,2)],related:["three-body"],measurements:["T"],tryThis:"Tilt inclination."}),
C({id:"gravitational-lensing",slug:"gravitational-lensing",title:"Black Hole Lensing",category:"astrophysics",difficulty:"advanced",dimension:"3D",audioAvailable:true,aliases:["photon sphere"],simulationType:"educational-lens",tagline:"Educational visualization — not full GR ray tracing.",description:"Horizon, photon ring, schematic lensed ray.",intuition:"Light can circle at 1.5 rs.",explanation:"rs=2GM/c^2. Toy deflection.",theory:"Schwarzschild scales.",assumptions:["Not integrated geodesics"],equations:[{latex:"rs=2GM/c^2",meaning:"Schwarzschild radius.",symbols:"photon sphere 1.5 rs"}],parameters:[P("M","Mass","Msun",4,40,0.5,12),P("impact","Impact param","x rs",1.6,8,0.1,3)],related:["black-hole"],measurements:["rs","rph"],tryThis:"Drop impact toward 1.5."}),
C({id:"expanding-universe",slug:"expanding-universe",title:"Expanding Universe",category:"cosmology",difficulty:"intermediate",dimension:"3D",aliases:["hubble","scale factor"],simulationType:"comoving-grid",tagline:"Comoving galaxies; space grows.",description:"Not an explosion from a center.",intuition:"Every galaxy sees others recede.",explanation:"a(t)=exp(H0 t) toy de Sitter.",theory:"FLRW cartoon.",assumptions:["Constant H0"],equations:[{latex:"d_phys=a(t) chi",meaning:"Physical vs comoving.",symbols:"a scale factor"}],parameters:[P("H0","H0 scale","",0.05,0.6,0.01,0.2),P("t","Time","",0,8,0.05,1.2)],related:["star-system-3d"],measurements:["a","z"],tryThis:"Read the caption. Nothing flies from the origin."}),
];
