import type { Concept } from "./concepts-types";
const P = (key: string, label: string, unit: string, min: number, max: number, step: number, def: number) => ({ key, label, unit, min, max, step, default: def });
const C = (x: Concept) => x;
export const PART: Concept[] = [
C({id:"lens",slug:"lens",title:"Thin Lens",category:"optics",difficulty:"beginner",
tagline:"Paraxial rays and the thin-lens equation.",
description:"Move an object in front of a thin lens.",
intuition:"Closer than f — virtual and upright. Farther — real and inverted.",
explanation:"1/f = 1/s + 1/s′. Rays, not full wave optics.",
theory:"First-order optics. Aberrations omitted.",
assumptions:["Thin lens","Paraxial rays"],
equations:[{latex:"1/f=1/s+1/s'",meaning:"Thin-lens equation.",symbols:"f, s, s′"}],
parameters:[P("f","Focal length","cm",4,30,0.5,12),P("s","Object distance","cm",5,60,0.5,24)],
related:["double-slit"],measurements:["sprime","M"]}),
C({id:"electric-field",slug:"electric-field",title:"Electric Field",category:"electromagnetism",difficulty:"intermediate",
tagline:"Place charges. The field is force per unit charge.",
description:"Two point charges with field arrows.",
intuition:"Field arrows leave + and enter −.",
explanation:"E(r) = Σ k qi (r−ri)/|r−ri|³.",
theory:"Vacuum electrostatics. Superposition is linear.",
assumptions:["Vacuum","Point charges","No magnetism"],
equations:[{latex:"\\mathbf E=k q\\hat r/r^2",meaning:"Coulomb field.",symbols:"k=1/(4πε0)"}],
parameters:[P("q1","Charge 1","nC",-20,20,0.5,8),P("q2","Charge 2","nC",-20,20,0.5,-8),P("sep","Separation","cm",4,24,0.5,12)],
related:["magnetic-field","simple-circuit"],measurements:["Emid"]}),
C({id:"magnetic-field",slug:"magnetic-field",title:"Magnetic Field & Lorentz Force",category:"electromagnetism",difficulty:"intermediate",
tagline:"v × B bends charge into circles.",
description:"A charged particle in uniform B into the page.",
intuition:"Perpendicular speed becomes a cyclotron orbit.",
explanation:"F = q(E + v × B). ω = qB/m, r = mv⊥/|q|B.",
theory:"Non-relativistic Lorentz force.",
assumptions:["Uniform B","Non-relativistic"],
equations:[{latex:"\\mathbf F=q(\\mathbf E+\\mathbf v\\times\\mathbf B)",meaning:"Lorentz force.",symbols:"q (C), B (T)"}],
parameters:[P("q","Charge sign","e",-2,2,1,1),P("B","B field","mT",0.2,8,0.1,2),P("v","Speed","km/s",10,400,5,80),P("mass","Mass scale","u",1,20,0.5,1)],
related:["electric-field"],measurements:["r_cyc","omega"]}),
C({id:"simple-circuit",slug:"simple-circuit",title:"Simple RC Circuit",category:"electromagnetism",difficulty:"beginner",
tagline:"Capacitors remember voltage; resistors set the clock.",
description:"Charge an RC circuit. τ = RC.",
intuition:"Big C or big R — the voltage crawls.",
explanation:"Vc(t) = V(1−e^{−t/RC}) while charging.",
theory:"Lumped-element Kirchhoff circuit.",
assumptions:["Ideal R and C","No inductance"],
equations:[{latex:"\\tau=RC",meaning:"Time constant.",symbols:"R (Ω), C (F)"}],
parameters:[P("R","Resistance","kΩ",0.5,50,0.5,10),P("C","Capacitance","μF",1,200,1,47),P("V","Source V","V",1,24,0.5,5)],
related:["electric-field"],measurements:["tau","Vc"]}),
C({id:"ideal-gas",slug:"ideal-gas",title:"Ideal Gas",category:"thermodynamics",difficulty:"beginner",
tagline:"PV = nRT, drawn as colliding particles.",
description:"A 2D box of hard disks. T sets kinetic energy. Educational visualization, not full MD.",
intuition:"Heat them — they slam the walls harder.",
explanation:"Reported P comes from the ideal-gas law. Animation is a 2D toy.",
theory:"Kinetic theory cartoon, not 3D MD.",
assumptions:["Ideal gas EOS","2D animation"],
equations:[{latex:"PV=nRT",meaning:"Ideal gas law.",symbols:"P (Pa), V (m³), T (K)"}],
parameters:[P("T","Temperature","K",80,600,5,300),P("n","Amount","mol",0.2,4,0.1,1),P("V","Volume","L",5,50,1,22.4),P("Nshow","Drawn particles","",20,180,5,70)],
related:["entropy"],measurements:["P","vrms"]}),
C({id:"entropy",slug:"entropy",title:"Entropy Visualization",category:"thermodynamics",difficulty:"intermediate",
tagline:"Two chambers. Remove the divider.",
description:"Lattice-gas mixing cartoon of multiplicity.",
intuition:"The mixed state has more microstates.",
explanation:"S = k ln Ω for a toy two-box model.",
theory:"Boltzmann entropy. Finite-N irreversibility is probable, not absolute.",
assumptions:["Toy two-box model"],
equations:[{latex:"S=k\\ln\\Omega",meaning:"Boltzmann entropy.",symbols:"k Boltzmann constant"}],
parameters:[P("N","Particles","",8,80,1,24),P("open","Divider open","",0,1,1,1)],
related:["ideal-gas"],measurements:["S","left"]}),
C({id:"time-dilation",slug:"time-dilation",title:"Time Dilation",category:"relativity",difficulty:"intermediate",
tagline:"Moving clocks run slow.",
description:"A light clock on a train. Boost β = v/c toward 1.",
intuition:"The moving clock’s light path is longer, so each tick takes more lab time.",
explanation:"γ = 1/√(1−β²). Δt = γ Δτ. Nothing exceeds c.",
theory:"Special relativity. Proper time belongs to the clock’s worldline.",
assumptions:["Inertial frames","No gravity"],
equations:[{latex:"\\Delta t=\\gamma\\Delta\\tau",meaning:"Time dilation.",symbols:"γ=1/√(1−v²/c²)"}],
parameters:[P("beta","v/c","",0,0.995,0.005,0.6)],
related:["length-contraction","spacetime-diagram"],measurements:["gamma","tLab","tProper"]}),
];
