import type { Concept } from "./concepts-types";
const P = (key: string, label: string, unit: string, min: number, max: number, step: number, def: number) => ({ key, label, unit, min, max, step, default: def });
const C = (x: Concept) => x;
export const PART: Concept[] = [
C({id:"newtons-second-law",slug:"newtons-second-law",title:"Newton's Second Law",category:"mechanics",difficulty:"beginner",
tagline:"Force changes momentum. For constant mass, F = ma.",
description:"Apply a net force to a block and watch acceleration respond instantly.",
intuition:"Twice the force, twice the acceleration. Twice the mass, half the acceleration if force is unchanged.",
explanation:"Generally F = dp/dt. Constant mass gives F = ma. The lab integrates a = F/m with semi-implicit Euler.",
theory:"In an inertial frame net force equals the time derivative of linear momentum.",
assumptions:["Constant mass","Inertial frame","Optional kinetic friction f = μN"],
equations:[{latex:"F = ma",meaning:"Net force equals mass times acceleration.",symbols:"F (N), m (kg), a (m/s²)"}],
parameters:[P("mass","Mass","kg",0.2,20,0.1,2),P("force","Force","N",-40,40,0.5,10),P("mu","Friction μ","",0,0.8,0.01,0)],
related:["conservation-of-energy","projectile-motion"],measurements:["a","v","x"]}),
C({id:"projectile-motion",slug:"projectile-motion",title:"Projectile Motion",category:"mechanics",difficulty:"beginner",
tagline:"A parabola in uniform gravity — until drag appears.",
description:"Launch a projectile. Compare the numerical path to the analytic parabola.",
intuition:"Without drag, horizontal velocity is constant. Vertical motion is free fall.",
explanation:"x = v0 cosθ t, y = y0 + v0 sinθ t − ½gt². Quadratic drag shortens the range.",
theory:"Newton II in components. No-drag integrator must match closed-form range within tolerance.",
assumptions:["Flat ground","Constant g","Optional quadratic drag"],
equations:[{latex:"x=v_0\\cos\\theta t",meaning:"Horizontal motion without drag.",symbols:"v0 (m/s), θ (rad)"}],
parameters:[P("v0","Launch speed","m/s",1,80,0.5,25),P("angle","Angle","deg",5,85,1,45),P("g","Gravity","m/s²",1.6,25,0.1,9.81),P("drag","Drag c","kg/m",0,0.08,0.001,0),P("mass","Mass","kg",0.1,10,0.1,1)],
related:["newtons-second-law","conservation-of-energy"],measurements:["range","hmax","tof"],hypotheticalNote:"Changing g is a what-if, not Earth."}),
C({id:"conservation-of-energy",slug:"conservation-of-energy",title:"Conservation of Energy",category:"mechanics",difficulty:"beginner",
tagline:"A roller on a track trades height for speed.",
description:"Kinetic and potential energy swap while their sum stays flat when friction is off.",
intuition:"What you lose in height you gain in speed.",
explanation:"E = ½mv² + mgh is conserved when non-conservative work is zero.",
theory:"Work–energy theorem. Conservative forces imply dE/dt = 0.",
assumptions:["1D height track","Optional friction"],
equations:[{latex:"E=\\tfrac12 mv^2+mgh",meaning:"Mechanical energy.",symbols:"m (kg), v (m/s), h (m)"}],
parameters:[P("mass","Mass","kg",0.2,10,0.1,1),P("h0","Start height","m",2,12,0.1,8),P("g","Gravity","m/s²",1.6,20,0.1,9.81),P("mu","Friction μ","",0,0.3,0.01,0)],
related:["pendulum","projectile-motion"],measurements:["K","U","E"]}),
C({id:"pendulum",slug:"pendulum",title:"Pendulum",category:"mechanics",difficulty:"intermediate",
tagline:"Not a sine wave unless the swing is small.",
description:"Nonlinear pendulum with damping. Compare period to 2π√(L/g).",
intuition:"Large amplitudes take longer.",
explanation:"θ̈ + (g/L) sinθ = 0. RK4 integrates the nonlinear ODE.",
theory:"Lagrangian L = ½mL²θ̇² − mgL(1−cosθ).",
assumptions:["Massless rod","Point bob","Optional linear damping"],
equations:[{latex:"\\ddot\\theta=-(g/L)\\sin\\theta",meaning:"Exact equation of motion.",symbols:"θ (rad), L (m)"}],
parameters:[P("L","Length","m",0.3,4,0.05,1.2),P("theta0","Start angle","deg",2,170,1,40),P("g","Gravity","m/s²",1.6,20,0.1,9.81),P("damp","Damping","1/s",0,1.2,0.01,0.05)],
related:["conservation-of-energy","standing-waves"],measurements:["theta","omega","Tsmall"]}),
C({id:"orbital-motion",slug:"orbital-motion",title:"Orbital Motion",category:"mechanics",difficulty:"intermediate",
tagline:"Gravity as an inverse-square central force.",
description:"A planet around a fixed star. Change speed and watch bound or escaping paths.",
intuition:"Too slow — fall in. Too fast — leave.",
explanation:"Integrates a = −GM r̂ / r². Closed ellipses need inverse-square gravity.",
theory:"Kepler III and angular-momentum conservation for central forces.",
assumptions:["Fixed central mass","Point masses","No GR precession"],
equations:[{latex:"\\mathbf a=-GM\\hat r/r^2",meaning:"Newtonian gravity.",symbols:"G, M, r"}],
parameters:[P("speed","Orbit speed scale","× v_circ",0.4,1.6,0.01,1),P("M","Star mass","M☉",0.3,5,0.1,1)],
related:["solar-system","black-hole"],measurements:["r","v"]}),
C({id:"wave-interference",slug:"wave-interference",title:"Wave Interference",category:"waves",difficulty:"beginner",
tagline:"Two sources, one field: crests add or cancel.",
description:"Superpose two traveling waves. Tune frequency, phase and amplitude.",
intuition:"Same phase — louder. Opposite phase — quieter.",
explanation:"Linear superposition: displacements add.",
theory:"Exact for linear media.",
assumptions:["1D linear medium","No dissipation"],
equations:[{latex:"y=y_1+y_2",meaning:"Linear superposition.",symbols:"displacements add"}],
parameters:[P("A1","Amplitude 1","m",0,1.5,0.05,1),P("A2","Amplitude 2","m",0,1.5,0.05,1),P("f1","Frequency 1","Hz",0.2,3,0.05,1),P("f2","Frequency 2","Hz",0.2,3,0.05,1.15),P("phase","Phase 2","deg",0,360,1,0)],
related:["standing-waves","double-slit"],measurements:["beat"]}),
C({id:"standing-waves",slug:"standing-waves",title:"Standing Waves",category:"waves",difficulty:"intermediate",
tagline:"Nodes that refuse to move.",
description:"A string fixed at both ends. Change harmonic number.",
intuition:"Only wavelengths that fit survive.",
explanation:"y = 2A sin(nπx/L) cos(ωt) with ω = nπv/L.",
theory:"Boundary conditions y(0)=y(L)=0 select modes.",
assumptions:["Ideal string","Fixed ends"],
equations:[{latex:"\\lambda_n=2L/n",meaning:"Allowed wavelengths.",symbols:"n = 1,2,3…"}],
parameters:[P("n","Harmonic n","",1,8,1,2),P("L","Length","m",0.5,4,0.1,2),P("v","Wave speed","m/s",20,400,5,120),P("A","Amplitude","m",0.05,0.6,0.01,0.25)],
related:["wave-interference","particle-in-a-box"],measurements:["freq","lambda"]}),
C({id:"double-slit",slug:"double-slit",title:"Double-Slit Interference",category:"optics",difficulty:"intermediate",
tagline:"Fringes from path difference.",
description:"Classical wave intensity on a screen.",
intuition:"Path difference λ is bright; λ/2 is dark.",
explanation:"Fraunhofer pattern I ∝ sinc²(β) cos²(δ). Wave optics, not a photon-by-photon run.",
theory:"Huygens–Fresnel, two coherent sources.",
assumptions:["Monochromatic","Far field","Coherent source"],
equations:[{latex:"\\Delta y=\\lambda L/d",meaning:"Fringe spacing.",symbols:"λ, L, d"}],
parameters:[P("lambda","Wavelength","nm",380,700,5,550),P("d","Slit spacing","μm",20,400,5,120),P("a","Slit width","μm",5,80,1,20),P("L","Screen distance","m",0.4,4,0.1,1.2)],
related:["quantum-double-slit","wave-interference"],measurements:["fringe"]}),
];
