import type { SimState } from "./sim-state";
import { doublePendulumEnergy, qhoPsi } from "./physics-advanced";
import { defaultCam, project3, type Cam3 } from "./camera3d";
function cam(s: SimState): Cam3 { if (!s.data.cam) s.data.cam = defaultCam(7); return s.data.cam as Cam3; }
function finite(n: number, fb = 0) { return Number.isFinite(n) ? n : fb; }
export function drawAdvanced(ctx: CanvasRenderingContext2D, w: number, h: number, slug: string, s: SimState) {
  const p=s.params; const c=cam(s);
  ctx.fillStyle="#9aa4b8"; ctx.font="12px ui-monospace,monospace";
  const axes=()=>{ const o=project3(0,0,0,c,w,h); const X=project3(1.6,0,0,c,w,h); const Y=project3(0,1.6,0,c,w,h); const Z=project3(0,0,1.6,c,w,h);
    ctx.strokeStyle="#5a3030"; ctx.beginPath(); ctx.moveTo(o.x,o.y); ctx.lineTo(X.x,X.y); ctx.stroke();
    ctx.strokeStyle="#305a30"; ctx.beginPath(); ctx.moveTo(o.x,o.y); ctx.lineTo(Y.x,Y.y); ctx.stroke();
    ctx.strokeStyle="#30305a"; ctx.beginPath(); ctx.moveTo(o.x,o.y); ctx.lineTo(Z.x,Z.y); ctx.stroke(); };
  if (slug==="elastic-collision") { ctx.fillStyle="#6ee7ff"; ctx.fillRect(w/2+(s.data.x1??0)*80-16,h/2-16,32,32); ctx.fillStyle="#ffb86b"; ctx.fillRect(w/2+(s.data.x2??0)*80-16,h/2-16,32,32); }
  else if (slug==="projectile-drag") { ctx.strokeStyle="#6ee7ff"; ctx.beginPath(); s.trail.forEach((pt,i)=>{ const X=40+pt.x*6,Y=h-30-pt.y*6; if(i===0)ctx.moveTo(X,Y); else ctx.lineTo(X,Y);}); ctx.stroke(); ctx.fillText("cyan = quadratic drag",16,20); }
  else if (slug==="double-pendulum") { const en=doublePendulumEnergy(s.data.y??[0,0,0,0],{m1:p.m1,m2:p.m2,L1:p.L1,L2:p.L2,g:9.81}); const sc=Math.min(w,h)*0.18; ctx.strokeStyle="#9aa4b8"; ctx.beginPath(); ctx.moveTo(w/2,50); ctx.lineTo(w/2+en.x1*sc,50-en.y1*sc); ctx.lineTo(w/2+en.x2*sc,50-en.y2*sc); ctx.stroke(); ctx.fillStyle="#ffb86b"; ctx.beginPath(); ctx.arc(w/2+en.x2*sc,50-en.y2*sc,7,0,6.28); ctx.fill(); }
  else if (slug==="three-body") { axes(); (s.data.bodies??[]).forEach((b: {x:number;y:number;z:number},i:number)=>{ const q=project3(b.x,b.y,b.z,c,w,h); ctx.fillStyle=["#6ee7ff","#ffb86b","#c4b5fd"][i]; ctx.beginPath(); ctx.arc(q.x,q.y,6,0,6.28); ctx.fill(); }); ctx.fillText("Numerical three-body simulation",12,h-12); }
  else if (slug==="gyroscope") { axes(); const pre=s.data.pre??0; const tip=project3(Math.sin(pre)*1.4,1.6,Math.cos(pre)*1.4,c,w,h); const o=project3(0,0,0,c,w,h); ctx.strokeStyle="#6ee7ff"; ctx.beginPath(); ctx.moveTo(o.x,o.y); ctx.lineTo(tip.x,tip.y); ctx.stroke(); ctx.fillStyle="#ffb86b"; ctx.beginPath(); ctx.arc(tip.x,tip.y,8,0,6.28); ctx.fill(); ctx.fillText("Steady precession toy — nutation omitted",12,h-12); }
  else if (slug==="wave-surface") { axes(); ctx.strokeStyle="#6ee7ff66"; const k=s.data.k??1,om=s.data.omega??1; for(let i=-4;i<=4;i++){ ctx.beginPath(); for(let j=-4;j<=4;j++){ const z=p.A*Math.sin(k*i-om*s.t); const q=project3(i*0.4,z,j*0.4,c,w,h); if(j===-4)ctx.moveTo(q.x,q.y); else ctx.lineTo(q.x,q.y);} ctx.stroke(); } }
  else if (slug==="electric-field-3d") { axes(); const q1=project3(-p.sep/2,0,0,c,w,h), q2=project3(p.sep/2,0,0,c,w,h); ctx.fillStyle=p.q1>=0?"#ffb86b":"#6ee7ff"; ctx.beginPath(); ctx.arc(q1.x,q1.y,8,0,6.28); ctx.fill(); ctx.fillStyle=p.q2>=0?"#ffb86b":"#6ee7ff"; ctx.beginPath(); ctx.arc(q2.x,q2.y,8,0,6.28); ctx.fill(); }
  else if (slug==="magnetic-wire") { axes(); const a=project3(0,-2,0,c,w,h),b=project3(0,2,0,c,w,h); ctx.strokeStyle="#ffb86b"; ctx.beginPath(); ctx.moveTo(a.x,a.y); ctx.lineTo(b.x,b.y); ctx.stroke(); ctx.strokeStyle="#6ee7ff88"; for(const r of [0.6,1.1]){ ctx.beginPath(); for(let t=0;t<=24;t++){ const ang=t/24*6.28*Math.sign(p.I||1); const q=project3(r*Math.cos(ang),0,r*Math.sin(ang),c,w,h); if(t===0)ctx.moveTo(q.x,q.y); else ctx.lineTo(q.x,q.y);} ctx.stroke(); } }
  else if (slug==="electromagnetic-wave") { axes(); ctx.strokeStyle="#6ee7ff"; ctx.beginPath(); for(let i=-8;i<=8;i++){ const z=i*0.28; const E=p.E0*Math.cos((2*Math.PI/p.lambda)*z-s.t*3); const q=project3(0,E,z,c,w,h); if(i===-8)ctx.moveTo(q.x,q.y); else ctx.lineTo(q.x,q.y);} ctx.stroke(); ctx.strokeStyle="#ffb86b"; ctx.beginPath(); for(let i=-8;i<=8;i++){ const z=i*0.28; const B=p.E0*Math.cos((2*Math.PI/p.lambda)*z-s.t*3); const q=project3(B,0,z,c,w,h); if(i===-8)ctx.moveTo(q.x,q.y); else ctx.lineTo(q.x,q.y);} ctx.stroke(); ctx.fillText("cyan E, amber B, k along z",12,h-12); }
  else if (slug==="ray-tracing-3d") { axes(); const lens=project3(0,0,0,c,w,h); ctx.strokeStyle="#6ee7ff"; ctx.beginPath(); ctx.ellipse(lens.x,lens.y,14,40,0,0,6.28); ctx.stroke(); ctx.fillText("Geometric optics — not a photoreal tracer",12,h-12); }
  else if (slug==="hydrogen-orbitals") { axes(); ctx.fillStyle="#6ee7ff"; for (const pt of s.data.cloud??[]) { const q=project3(pt.x*0.22,pt.y*0.22,pt.z*0.22,c,w,h); ctx.fillRect(q.x,q.y,2,2);} ctx.fillStyle="#9aa4b8"; ctx.fillText("Probability-density visualization, not a classical electron orbit.",12,h-12); }
  else if (slug==="star-system-3d") { axes(); const star=project3(0,0,0,c,w,h); ctx.fillStyle="#ffb86b"; ctx.beginPath(); ctx.arc(star.x,star.y,10,0,6.28); ctx.fill(); const inc=p.inc*Math.PI/180,ang=s.data.ang??0; const pl=project3(2.2*Math.cos(ang),2.2*Math.sin(ang)*Math.sin(inc),2.2*Math.sin(ang)*Math.cos(inc),c,w,h); ctx.fillStyle="#6ee7ff"; ctx.beginPath(); ctx.arc(pl.x,pl.y,5,0,6.28); ctx.fill(); ctx.fillText("Scaled educational orbital model.",12,h-12); }
  else if (slug==="gravitational-lensing") { axes(); const hole=project3(0,0,0,c,w,h); ctx.fillStyle="#000"; ctx.beginPath(); ctx.arc(hole.x,hole.y,22,0,6.28); ctx.fill(); ctx.strokeStyle="#6ee7ff"; ctx.beginPath(); ctx.arc(hole.x,hole.y,22,0,6.28); ctx.stroke(); ctx.strokeStyle="#ffb86b88"; ctx.beginPath(); ctx.arc(hole.x,hole.y,33,0,6.28); ctx.stroke(); ctx.fillStyle="#9aa4b8"; ctx.fillText("Schematic visualization — not full GR ray tracing. Educational sonification only.",12,h-14); }
  else if (slug==="expanding-universe") { axes(); for (const g of s.data.gals??[]) { const a=s.data.a??1; const q=project3(g.x*a*0.55,g.y*a*0.55,0,c,w,h); ctx.fillStyle="#6ee7ff"; ctx.beginPath(); ctx.arc(q.x,q.y,3,0,6.28); ctx.fill(); } ctx.fillStyle="#9aa4b8"; ctx.fillText("Comoving galaxies; expansion is not a central blast.",12,h-12); }
  else if (slug==="doppler-effect") { ctx.fillStyle="#ffb86b"; ctx.beginPath(); ctx.arc(w*0.35+(s.data.src??0),h/2,7,0,6.28); ctx.fill(); ctx.fillText(`Educational sonification  f_obs=${finite(s.data.fobs).toFixed(1)} Hz`,16,20); }
  else if (slug==="relativistic-doppler") { ctx.fillText(`Educational sonification  f'=${finite(s.data.fobs).toFixed(1)} Hz  z=${finite(s.data.z).toFixed(3)}`,16,40); }
  else if (slug==="molecular-dynamics") { ctx.strokeStyle="#3d4f6f"; ctx.strokeRect(20,16,w-40,h-32); for (const part of s.particles) { ctx.fillStyle="#6ee7ff"; ctx.beginPath(); ctx.arc(20+part.x*(w-40),16+part.y*(h-32),4,0,6.28); ctx.fill(); } }
  else if (slug==="maxwell-boltzmann") { ctx.fillText("analytic Maxwell-Boltzmann speed pdf",16,20); }
  else if (slug==="quantum-harmonic-oscillator") { ctx.strokeStyle="#6ee7ff"; ctx.beginPath(); for(let i=0;i<w;i++){ const x=(i/w-0.5)*8; const psi=qhoPsi(p.n,x,Math.max(0.1,p.omega)); if(i===0)ctx.moveTo(i,h/2-psi*70); else ctx.lineTo(i,h/2-psi*70);} ctx.stroke(); }
  else if (slug==="rolling-motion") { ctx.fillStyle="#6ee7ff"; ctx.beginPath(); ctx.arc(80+((s.data.v??0)%8)*20,h-70,16,0,6.28); ctx.fill(); ctx.fillText(String(s.data.kind??""),16,20); }
  else if (slug==="spacetime-explorer") { ctx.fillText("amber light cone / cyan worldline",16,20); }
  else if (slug==="stern-gerlach") { ctx.fillStyle="#6ee7ff"; ctx.fillRect(w*0.7,40,16,Math.min(h*0.4,(s.data.up??0)*3)); ctx.fillStyle="#ffb86b"; ctx.fillRect(w*0.78,40,16,Math.min(h*0.4,(s.data.down??0)*3)); }
  else { ctx.fillText(slug,16,20); }
}
